worker_processes auto;

events {
    worker_connections 1024;
}

http {
    # Definimos los dos servidores Apache
    upstream apache_backend {
        server apache1:80;
        server apache2:80;
    }

    # Configuración de la zona de caché
    proxy_cache_path /var/cache/nginx levels=1:2 keys_zone=my_cache:10m max_size=100m inactive=60m use_temp_path=off;

    server {
        listen 80;

        location / {
            proxy_pass http://apache_backend;
            
            # Cabeceras necesarias para el proxy
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;

            # --- CONFIGURACIÓN DE CACHÉ ---
            proxy_cache my_cache;
            proxy_cache_valid 200 10s; # La caché dura 10 segundos
            
            # --- CABECERAS PARA LA WEB ---
            # Esta línea permite que la web sepa qué servidor ha respondido
            add_header X-Served-By $upstream_addr;
            # Esta línea muestra si es HIT o MISS (tu captura anterior)
            add_header X-Cache $upstream_cache_status;
        }
    }
}