# =========================
# WORKER PROCESS (rendimiento)
# =========================
worker_processes auto;

events {
    worker_connections 1024;
}

http {
    # Definición de la ruta de caché
    proxy_cache_path /var/cache/nginx levels=1:2 keys_zone=my_cache:10m max_size=100m inactive=60m use_temp_path=off;

    # =========================
    # LOAD BALANCER (BACKENDS)
    # =========================
    upstream apache_backend {
        server apache1:80;
        server apache2:80;
    }

    server {
        listen 80;

        location / {
            proxy_pass http://apache_backend;

            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;

            # =========================
            # CONFIGURACIÓN DE CACHÉ (10s)
            # =========================
            proxy_cache my_cache;              
            proxy_cache_valid 200 10s; 
            
            # Headers para comprobación en F12 y para el Script de la web
            add_header X-Cache $upstream_cache_status;
            add_header X-Servidor $upstream_addr; # <--- ESTA LÍNEA ES CLAVE
        }
    }
}